### PR TITLE
use well_known[m.homeserver].base_url instead of home_server for cont…

### LINKED ISSUE #7: wrong home_server domain in localstorage
Hello, thank you for this nice matrix admin panel!

I noticed that for some reason the `home_server` variable that's stored in local storage gets set with a wrong value with our instance.

Our synapse server answers at `matrix.example.com`, but the value in local storage gets set to `example.com`.
When I change the value by hand, everything works fine. What's weird is that login works fine...
Only after login I got errors about unable to fetch resource (it's trying the wrong domain ofc)

Is this value taken from the synapse instance? Is this a bug or a misconfiguration of our synapse server?

### PR DESCRIPTION
**Pull request by teutat3s**
…acting the synapse server

Fixes #7 

Please excuse if the code isn't perfect, I'm still learning a lot and would be happy to improve it if possible, feedback is always welcome.

### Suggestions: 
- use `well_known[m.homeserver].base_url` from `matrix.YOUR.DOMAIN/_matrix/client/r0/login` instead of `home_server`
- this is to make synapse admin work with `matrix.YOUR.DOMAIN` instead of `YOUR.DOMAIN`
- also added a helper function to strip trailing slashes that can appear in `base_url`
- moved `https` checking into a function and use it when we first get the matrix URL, then store the correct `https://` URL in localstorage

### CODE REVIEW

**Comment by rhaamo** [comment]
When accessing the login page without anything already in cache, `stripTrailingSlash` fails because `str` is null.
Didn't investigated much, I just added a return if `!str` to workaround.

**Comment by teutat3s** [comment]
> When accessing the login page without anything already in cache, `stripTrailingSlash` fails because `str` is null.
> Didn't investigated much, I just added a return if `!str` to workaround.

Thank you for the hint, implemented as you suggested

Regarding this PR, I did improvements to my previous commit, now we check early if the URL was entered without `https` or if it's missing in the json we get from synapse (which probably shouldn't happen, but good to make sure) and add the correct url with `https` and without trailing spaces to localstorage, from where we can easily access it.

In my opinion using the well_known entry from the json for the homeserver address is the right way to go.

I'm looking forward for feedback.

**Comment by awesome-manuel** [comment]
@teutat3s please add me or @awesome-michael as reviewer when you think it's ready.

**Comment by teutat3s** [comment]
Thanks for the review, could you point me to the code where `home_server` is used - I don't know where that part of the logic happens.

**Comment by teutat3s** [comment]
Testing create user form looks like it's not auto-detecting the `home_server`

Screenshot 2020-02-12 at 14 38 33

**Comment by awesome-michael** [comment]
Right.. the parts that need the domain part of the user id are not (yet) in the master branch.

File: src/synapse/authProvider.js [hunk 1]
```diff
@@ -1,5 +1,22 @@
 import { fetchUtils } from "react-admin";
 
+const ensureHttpsForUrl = (url) => {
+  if (/^https:\/\//i.test(url)) {
```
Comment (awesome-manuel) [inline src/synapse/authProvider.js]: This `if` is probably not required, since the `replace` will simply replace https:// by https://

File: src/synapse/authProvider.js [hunk 2]
```diff
@@ -13,16 +30,13 @@ const authProvider = {
...
 
-    // add 'https://' to homeserver url if its missing
-    let newUrl = window.decodeURIComponent(homeserver);
-    newUrl = newUrl.trim().replace(/\s/g, "");
-    if (!/^https?:\/\//i.test(newUrl)) {
-      homeserver = `https://${newUrl}`;
-    }
+    const url = window.decodeURIComponent(homeserver);
+    const trimmed_url = url.trim().replace(/\s/g, "");
+    const homeserver_url = ensureHttpsForUrl(trimmed_url) + "/_matrix/client/r0/login";
```
Comment (awesome-manuel) [inline src/synapse/authProvider.js]: Better rename to `login_api_url`

File: src/synapse/authProvider.js [hunk 3]
```diff
@@ -13,16 +30,13 @@ const authProvider = {
...
 
-    const url = homeserver + "/_matrix/client/r0/login";
-    return fetchUtils.fetchJson(url, options).then(({ json }) => {
-      localStorage.setItem("home_server", json.home_server);
+    return fetchUtils.fetchJson(homeserver_url, options).then(({ json }) => {
+      const normalized_base_url = ensureHttpsForUrl(stripTrailingSlash(json.well_known["m.homeserver"].base_url))
```
Comment (awesome-manuel) [inline src/synapse/authProvider.js]: If the `base_url` does not start with `https://` this is probably a server misconfiguration. So I don't think we should try to be smarter than the server admin here.

File: src/synapse/authProvider.js [hunk 4]
```diff
@@ -13,16 +30,13 @@ const authProvider = {
...
+      localStorage.setItem("home_server", normalized_base_url);
```
Comment (awesome-manuel) [inline src/synapse/authProvider.js]: Should be `localStorage.setItem("home_server_url", ...)`

File: src/synapse/authProvider.js (hunk 1 above)
Comment (teutat3s) [reply src/synapse/authProvider.js]: I thought of return early & often here - in a [regex tester](https://www.regextester.com/93652) `/http?:\/\//g` only matches `http://` but not `https://` so we only replace if necessary

**Comment by teutat3s** [comment]
Thank you for all the feedback and sorry for the delay - I was away on holidays. 

Please check if everything is fine now - I tried implementing all requested changes, like adding `base_url` and smaller fixes that @awesome-manuel requested.

File: src/synapse/authProvider.js (hunk 1 above)
Comment (awesome-manuel) [reply src/synapse/authProvider.js]: Right, so either remove the `?` after `http` in line 7 or put a `.` in front of it. Right now it makes the `p` optional which is not what we want.
